### ISSUE TITLE
Quit fetch command Release selection

### ISSUE THREAD

**Issue by gronke** [bsdci/ioc#27]
It should be possible to leave the Release selection, that occurs when fetching releases, by entering `q` instead of any listed release identifier.

### Current Result
```
Press [Enter] to fetch the default selection (12.0-RELEASE) [1]: q
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ioc_cli/fetch.py", line 102, in cli
    release = prompts.release()
  File "/usr/local/lib/python3.6/site-packages/libioc/Prompts.py", line 70, in release
    return available_releases[int(selection)]
ValueError: invalid literal for int() with base 10: 'q'
```

**Comment by igalic** [comment]
or Ctr+C?
