### ISSUE TITLE
ioc binary hard-codes python3.6

### ISSUE THREAD

**Issue by igalic** [bsdci/ioc#46]
when installing `ioc` on FreeBSD-12.1-RELEASE, trying to run it will yield:

```root@freebsd:~ # ioc
ioc: Command not found.
root@freebsd:~ # /usr/local/bin/ioc
/usr/local/bin/ioc: Command not found.
root@freebsd:~ # 
```

the reason is that the python version is hard-coded, and with 12.1 it's wrong:

```python
#!/usr/local/bin/python3.6
import sys
import os.path

LIB_DIR = "/usr/local/lib/ioc"

if LIB_DIR.startswith("/") is False:
    __dirname = os.path.dirname(os.path.abspath(__file__))
    LIB_DIR = "/usr/local/lib/ioc"

# etc…
```

**Comment by karpa13a** [comment]
@igalic even if you change head to use python3.7 - binary package stays unusable:
```
root@host01:~ # ioc help
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 13, in <module>
    from ioc_cli import cli
  File "/usr/local/lib/ioc/ioc_cli/__init__.py", line 43, in <module>
    from libioc.Datasets import Datasets
  File "/usr/local/lib/python3.7/site-packages/libioc/Datasets.py", line 31, in <module>
    import libioc.helpers
  File "/usr/local/lib/python3.7/site-packages/libioc/helpers.py", line 37, in <module>
    import jail as libjail
ModuleNotFoundError: No module named 'jail'
```

or package rebuild is needed?

**Comment by gronke** [comment]
Will repackage all those dependencies with dynamic Python versions.
